# Generated by Django 3.1 on 2021-01-25 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.ImageField(default=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 1, 25, 18, 59, 45, 734118, tzinfo=utc))),
            ],
        ),
    ]
