# Generated by Django 3.1 on 2021-01-25 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorders',
            name='amount',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='customorders',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 19, 1, 52, 738714, tzinfo=utc)),
        ),
    ]
