# Generated by Django 3.1 on 2021-01-25 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210125_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorders',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 19, 2, 19, 559514, tzinfo=utc)),
        ),
    ]
