# Generated by Django 3.1 on 2021-01-25 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210125_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 1, 25, 19, 3, 36, 708395, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='CustomOrders',
        ),
    ]
